export const products = [
  {
    id: 1,
    name: "Modern Velvet Sofa",
    category: "Sofas",
    price: 1299,
    image: "/modern-velvet-sofa.jpg",
    description:
      "Luxurious velvet sofa with deep seating and elegant design. Perfect for contemporary living spaces.",
    featured: true,
    sale: false,
  },
  {
    id: 2,
    name: "Scandinavian Dining Chair",
    category: "Chairs",
    price: 249,
    salePrice: 199,
    image: "/scandinavian-dining-chair.png",
    description: "Minimalist dining chair with solid wood legs and comfortable upholstered seat.",
    featured: true,
    sale: true,
  },
  {
    id: 3,
    name: "Marble Coffee Table",
    category: "Tables",
    price: 599,
    image: "/marble-coffee-table.png",
    description: "Elegant coffee table featuring genuine marble top and brass-finished metal base.",
    featured: true,
    sale: false,
  },
  {
    id: 4,
    name: "Upholstered King Bed",
    category: "Beds",
    price: 1899,
    image: "/upholstered-king-bed.jpg",
    description:
      "Sophisticated upholstered bed frame with tufted headboard and solid wood construction.",
    featured: true,
    sale: false,
  },
  {
    id: 5,
    name: "Leather Lounge Chair",
    category: "Chairs",
    price: 899,
    salePrice: 699,
    image: "/leather-lounge-chair.jpg",
    description:
      "Classic leather lounge chair with ottoman. Timeless design and premium materials.",
    featured: false,
    sale: true,
  },
  {
    id: 6,
    name: "Sectional Sofa",
    category: "Sofas",
    price: 2199,
    image: "/modern-sectional-sofa.png",
    description: "Spacious L-shaped sectional with plush cushions and durable fabric upholstery.",
    featured: false,
    sale: false,
  },
  {
    id: 7,
    name: "Oak Dining Table",
    category: "Tables",
    price: 1299,
    image: "/rustic-oak-table.png",
    description: "Solid oak dining table with natural finish. Seats 6-8 people comfortably.",
    featured: false,
    sale: false,
  },
  {
    id: 8,
    name: "Accent Armchair",
    category: "Chairs",
    price: 449,
    image: "/modern-accent-armchair.png",
    description: "Statement armchair with curved silhouette and luxurious fabric upholstery.",
    featured: false,
    sale: false,
  },
  {
    id: 9,
    name: "Platform Bed Frame",
    category: "Beds",
    price: 799,
    salePrice: 649,
    image: "/platform-bed-frame.jpg",
    description: "Low-profile platform bed with clean lines and integrated storage drawers.",
    featured: false,
    sale: true,
  },
  {
    id: 10,
    name: "Console Table",
    category: "Tables",
    price: 399,
    image: "/modern-console-table.jpg",
    description:
      "Sleek console table perfect for entryways. Features slim profile and metal frame.",
    featured: false,
    sale: false,
  },
  {
    id: 11,
    name: "Chesterfield Sofa",
    category: "Sofas",
    price: 1799,
    image: "/chesterfield-sofa.jpg",
    description: "Classic Chesterfield sofa with deep button tufting and rolled arms.",
    featured: false,
    sale: false,
  },
  {
    id: 12,
    name: "Bar Stool Set",
    category: "Chairs",
    price: 349,
    image: "/modern-bar-stools.jpg",
    description: "Set of 2 adjustable bar stools with swivel seats and footrests.",
    featured: false,
    sale: false,
  },
  {
    id: 13,
    name: "Mid-Century Sideboard",
    category: "Tables",
    price: 899,
    image: "/mid-century-modern-wooden-sideboard-with-brass-han.jpg",
    description: "Vintage-inspired sideboard with ample storage and iconic mid-century design.",
    featured: false,
    sale: false,
  },
  {
    id: 14,
    name: "Wingback Accent Chair",
    category: "Chairs",
    price: 649,
    salePrice: 499,
    image: "/elegant-wingback-chair-in-velvet-fabric.jpg",
    description: "Classic wingback chair upholstered in premium velvet with nailhead trim.",
    featured: false,
    sale: true,
  },
  {
    id: 15,
    name: "Canopy Bed Frame",
    category: "Beds",
    price: 2299,
    image: "/modern-four-poster-canopy-bed-frame.jpg",
    description: "Dramatic four-poster canopy bed with clean lines and metal construction.",
    featured: false,
    sale: false,
  },
  {
    id: 16,
    name: "Loveseat Sofa",
    category: "Sofas",
    price: 899,
    image: "/compact-loveseat-sofa-in-neutral-fabric.jpg",
    description: "Compact loveseat perfect for small spaces. Comfortable and stylish.",
    featured: false,
    sale: false,
  },
  {
    id: 17,
    name: "Nesting Coffee Tables",
    category: "Tables",
    price: 449,
    image: "/set-of-nesting-coffee-tables-with-metal-frames.jpg",
    description: "Set of 3 nesting tables with marble tops and gold-finished metal frames.",
    featured: false,
    sale: false,
  },
  {
    id: 18,
    name: "Rocking Chair",
    category: "Chairs",
    price: 549,
    image: "/modern-rocking-chair-with-cushioned-seat.jpg",
    description: "Contemporary rocking chair with ergonomic design and plush cushioning.",
    featured: false,
    sale: false,
  },
];
